const realms = [
  ['Meadow of Beginnings','Green fields','Gorak the Rootbound','Rootheart Charm'], ['Ashen Mines','Molten caverns','Brakka Flame-Eater','Ember Core'], ['Whispering Woods','Ancient forest','The Moss Widow','Mosscloak'], ['Frozen Reach','Icy cliffs','Ymir Stonehide','Frost Titan Shard'], ['Sunken Ruins','Flooded temples','Drownmaw','Tidecaller Pearl'], ['Storm Citadel','Lightning towers','Voltus Prime','Storm Lens'], ["Ogre King's Throne",'Final fortress','Ogron, King of Ogres','Crown of the Ogre King']
];
const weapons = [['Rusty Sword',12,0,'Free starter weapon'],['Twin Daggers',20,80,'Fast dual strikes'],['War Hammer',35,180,'Stuns ogres'],['Storm Bow',50,320,'Ranged damage'],['SUNBLADE',90,500,'Most powerful weapon']];
const state = { section:0, level:0, coins:0, score:0, weapon:0, started:false, ogres:Array.from({length:7},()=>Array(10).fill(false)), materials:Array.from({length:7},()=>Array(10).fill(false)), bosses:Array.from({length:7},()=>Array(10).fill(false)), items:Array.from({length:7},()=>Array(10).fill(false)), unlocked:Array(70).fill(false), keys:{}, x:220, y:330, facing:1, lastAttack:0 };
state.unlocked[0] = true;
const $ = id => document.getElementById(id), levelIndex = () => state.section * 10 + state.level, ogreTotal = () => 3 + (state.level + 1) % 4, materialTotal = () => 4 + (state.level + 1) % 5;
const weapon = () => weapons[state.weapon];
function setStatus(message){ $('status').textContent = message; $('toast').textContent = message; $('toast').classList.add('show'); clearTimeout(setStatus.timer); setStatus.timer = setTimeout(()=>$('toast').classList.remove('show'),2600); }
function render(){ const realm=realms[state.section], index=levelIndex(), ogreDone=state.ogres[state.section][state.level], materialDone=state.materials[state.section][state.level]; $('coins').textContent=state.coins; $('score').textContent=state.score; $('weapon').textContent=weapon()[0]; $('realmName').textContent=realm[0]; $('themeName').textContent=realm[1]; $('bossName').textContent=realm[2]; $('levelNumber').textContent=String(state.level+1).padStart(2,'0'); $('ogreProgress').textContent=`${ogreDone?ogreTotal():0} / ${ogreTotal()}`; $('materialProgress').textContent=`${materialDone?materialTotal():0} / ${materialTotal()}`; $('ogreBar').style.width=`${ogreDone?100:0}%`; $('materialBar').style.width=`${materialDone?100:0}%`; renderMap(); renderShop(); renderCraft(); renderLeaderboard(); draw(); }
function renderMap(){ $('levelGrid').innerHTML=realms.map((realm,s)=>`<div class="section-column"><h3>${s+1}. ${realm[0]}</h3><div class="levels">${Array.from({length:10},(_,l)=>{const i=s*10+l, cls=!state.unlocked[i]?'locked':s===state.section&&l===state.level?'current':state.items[s][l]?'done':'';return `<button class="level ${cls}" data-level="${s}-${l}" ${!state.unlocked[i]?'disabled':''}>${l+1}</button>`}).join('')}</div></div>`).join(''); document.querySelectorAll('.level').forEach(b=>b.onclick=()=>{const [s,l]=b.dataset.level.split('-').map(Number);state.section=s;state.level=l;setStatus(`${realms[s][0]} - Level ${l+1} selected.`);render();}); }
function itemMarkup(item,i,craft=false){return `<div class="item ${state.weapon===i?'equipped':''}"><div><h3>${item[0]}</h3><p>${item[3]} · ${item[1]} damage ${item[2]?'· '+item[2]+' coins':''}</p></div><button data-weapon="${i}">${state.weapon===i?'Equipped':craft?'Craft / equip':'Buy / equip'}</button></div>`}
function renderShop(){ $('shopList').innerHTML=weapons.map((w,i)=>itemMarkup(w,i)).join('');document.querySelectorAll('#shopList [data-weapon]').forEach(b=>b.onclick=()=>buy(Number(b.dataset.weapon))); }
function renderCraft(){ $('inventory').textContent='Materials: '+Object.entries({Wood:0,Iron:0,Leather:0,Crystal:0,Ember:0,'Sun Shards':0}).map(([n])=>`${n} 0`).join('  ·  ');$('craftList').innerHTML=weapons.map((w,i)=>itemMarkup(w,i,true)).join('');document.querySelectorAll('#craftList [data-weapon]').forEach(b=>b.onclick=()=>buy(Number(b.dataset.weapon))); }
function renderLeaderboard(){const rows=[['Mira',4800,'7-10'],['CodeKnight',3600,'5-8'],['OgreBane',2250,'4-3'],['You',state.score,`${state.section+1}-${state.level+1}`]].sort((a,b)=>b[1]-a[1]);$('leaderboardList').innerHTML=rows.map((r,i)=>`<div class="rank"><b>${String(i+1).padStart(2,'0')}</b><strong>${r[0]}</strong><span>${r[1]} pts</span><span>${r[2]}</span></div>`).join('');}
function start(){state.started=true;setStatus('Level started. Gather materials, defeat ogres, then face the boss.');render();}
function gather(){if(!state.started)return setStatus('Press Start Adventure first.');if(state.materials[state.section][state.level])return setStatus('All materials collected in this level.');state.materials[state.section][state.level]=true;setStatus(`Collected ${materialTotal()} materials.`);render();}
function defeatOgres(){if(!state.started)return setStatus('Press Start Adventure first.');if(state.ogres[state.section][state.level])return setStatus('Every ogre here is already defeated.');state.ogres[state.section][state.level]=true;state.coins+=ogreTotal()*5;setStatus(`${ogreTotal()} ogres defeated! +${ogreTotal()*5} coins.`);render();}
function fightBoss(){if(!state.ogres[state.section][state.level]||!state.materials[state.section][state.level])return setStatus('Defeat all ogres and gather materials first.');if(state.bosses[state.section][state.level])return setStatus('Boss defeated. Pick up the special item.');state.bosses[state.section][state.level]=true;state.coins+=100;state.score+=100+state.section*50+state.level*10;setStatus(`${realms[state.section][2]} defeated! +100 coins.`);render();}
function takeItem(){if(!state.bosses[state.section][state.level])return setStatus('Defeat the boss to reveal the special item.');if(state.items[state.section][state.level])return setStatus('Special item already collected.');state.items[state.section][state.level]=true;if(levelIndex()<69)state.unlocked[levelIndex()+1]=true;setStatus(`Collected ${realms[state.section][3]}! Next level unlocked.`);render();}
function nextLevel(){if(!state.items[state.section][state.level])return setStatus('Pick up the boss item before continuing.');if(levelIndex()===69)return setStatus('You conquered all 70 levels!');state.level++;if(state.level===10){state.section++;state.level=0;}setStatus(`${realms[state.section][0]} - Level ${state.level+1} begins.`);render();}
function buy(i){if(!weapons[i][2]){state.weapon=i;return render();}if(state.coins<weapons[i][2])return setStatus(`${weapons[i][0]} costs ${weapons[i][2]} coins.`);state.coins-=weapons[i][2];state.weapon=i;setStatus(`${weapons[i][0]} equipped!`);render();}
function draw(){const c=$('gameCanvas'),ctx=c.getContext('2d'),w=c.width,h=c.height;ctx.clearRect(0,0,w,h);let sky=ctx.createLinearGradient(0,0,0,h);sky.addColorStop(0,'#122c4c');sky.addColorStop(1,'#87b9ad');ctx.fillStyle=sky;ctx.fillRect(0,0,w,h);ctx.fillStyle='#26475b';ctx.fillRect(0,300,w,150);ctx.fillStyle='#356d55';ctx.fillRect(0,385,w,65);for(let x=0;x<w;x+=75){ctx.fillStyle='#5eae77';ctx.fillRect(x,376,34,9);}ctx.fillStyle='#cbe7d7';ctx.globalAlpha=.65;ctx.beginPath();ctx.arc(675,75,35,0,Math.PI*2);ctx.fill();ctx.globalAlpha=1;for(let x=90;x<w;x+=160){ctx.fillStyle='#193b4c';ctx.fillRect(x,260,70,120);ctx.fillStyle='#275b62';ctx.fillRect(x-15,290,100,90);}drawHero(ctx);ctx.fillStyle='#f7c969';ctx.font='bold 16px Space Grotesk';ctx.fillText(`Realm ${state.section+1} · Level ${state.level+1}`,22,28);}
function drawHero(ctx){const x=state.x,y=state.y;ctx.save();ctx.translate(x,y);ctx.scale(state.facing,1);ctx.fillStyle='#61d7e7';ctx.fillRect(-20,-52,40,52);ctx.fillStyle='#f5b27d';ctx.beginPath();ctx.arc(0,-70,20,0,Math.PI*2);ctx.fill();ctx.fillStyle='#16243a';ctx.fillRect(5,-74,5,5);ctx.fillStyle='#f4cb62';ctx.fillRect(-17,0,13,9);ctx.fillRect(4,0,13,9);ctx.restore();}
function animate(){if(state.started&&document.getElementById('adventure').classList.contains('active-view')){if(state.keys.a||state.keys.ArrowLeft){state.x=Math.max(30,state.x-4);state.facing=-1;}if(state.keys.d||state.keys.ArrowRight){state.x=Math.min(810,state.x+4);state.facing=1;}if(state.keys.w||state.keys.ArrowUp)state.y=Math.max(270,state.y-2);if(state.keys.s||state.keys.ArrowDown)state.y=Math.min(380,state.y+2);draw();}requestAnimationFrame(animate);}
document.querySelectorAll('.tab').forEach(tab=>tab.onclick=()=>{document.querySelectorAll('.tab').forEach(t=>t.classList.remove('active'));document.querySelectorAll('.view').forEach(v=>v.classList.remove('active-view'));tab.classList.add('active');$(tab.dataset.view).classList.add('active-view');});
$('startBtn').onclick=start;$('gatherBtn').onclick=gather;$('ogreBtn').onclick=defeatOgres;$('bossBtn').onclick=fightBoss;$('itemBtn').onclick=takeItem;$('nextBtn').onclick=nextLevel;
window.addEventListener('keydown',e=>{state.keys[e.key]=true;if(['j','J'].includes(e.key))attack('Quick attack',weapon()[1],0);if(['k','K'].includes(e.key))attack('Heavy attack',weapon()[1]*2,25);if(['l','L'].includes(e.key))attack('ABILITY',weapon()[1]*3,40);});window.addEventListener('keyup',e=>state.keys[e.key]=false);
function attack(name,damage,cost){const now=Date.now();if(now-state.lastAttack<300)return;state.lastAttack=now;setStatus(`${name}! ${damage} damage dealt.`);if(!state.ogres[state.section][state.level])defeatOgres();}
render();animate();

// Finished play mode: live enemies, collectables, boss health, and real progression.
const live = { section: 0, level: 0, started: false, x: 120, y: 350, vy: 0, facing: 1, grounded: true, keys: {}, stamina: 100, cooldown: 0, enemies: [], gems: [], boss: null };
const liveLevels = Array.from({ length: 70 }, () => ({ ogres: 0, materials: 0, boss: false, item: false }));
const liveUnlocked = Array(70).fill(false); liveUnlocked[0] = true;
const liveIndex = () => live.section * 10 + live.level;
const liveLevel = () => liveLevels[liveIndex()];
const liveTotals = () => ({ ogres: 3 + (live.level + 1) % 4, materials: 4 + (live.level + 1) % 5 });
function liveStatus(message) { $('status').textContent = message; $('toast').textContent = message; $('toast').classList.add('show'); clearTimeout(liveStatus.timer); liveStatus.timer = setTimeout(() => $('toast').classList.remove('show'), 2200); }
function liveStart() { live.started = true; live.x = 120; live.y = 350; live.vy = 0; liveSpawn(); liveStatus(`Level ${live.level + 1}: gather materials, defeat the ogres, then fight the boss.`); liveRender(); }
function liveSpawn() { const l = liveLevel(), t = liveTotals(); live.enemies = []; for (let n = l.ogres; n < t.ogres; n++) live.enemies.push({ x: 340 + n * 125, y: 350, hp: 45 + live.level * 5, max: 45 + live.level * 5, alive: true }); live.gems = []; for (let n = l.materials; n < t.materials; n++) live.gems.push({ x: 220 + n * 105, y: 330, taken: false }); live.boss = l.boss ? null : { x: 735, y: 350, hp: 230 + live.section * 45 + live.level * 8, max: 230 + live.section * 45 + live.level * 8, alive: true }; }
function liveCollect() { if (!live.started) return liveStatus('Press Start adventure first.'); const gem = live.gems.find(g => !g.taken && Math.abs(g.x - live.x) < 48 && Math.abs(g.y - live.y) < 55); if (!gem) return liveStatus('Move beside a glowing crystal and press E.'); gem.taken = true; liveLevel().materials++; liveStatus(`Material gathered: ${liveLevel().materials} / ${liveTotals().materials}`); liveRender(); }
function liveHit(type) { const now = performance.now(), cost = type === 'heavy' ? 20 : type === 'ability' ? 35 : 0; if (!live.started || now < live.cooldown) return; if (live.stamina < cost) return liveStatus('Not enough stamina.'); live.cooldown = now + (type === 'heavy' ? 500 : 260); live.stamina -= cost; const reach = type === 'ability' ? 220 : type === 'heavy' ? 125 : 90, damage = weapons[state.weapon][1] * (type === 'ability' ? 2.4 : type === 'heavy' ? 1.7 : 1), hitX = live.x + live.facing * reach; live.enemies.forEach(enemy => { if (enemy.alive && Math.abs(enemy.x - hitX) < reach && Math.abs(enemy.y - live.y) < 75) { enemy.hp -= damage; if (enemy.hp <= 0) { enemy.alive = false; liveLevel().ogres++; state.coins += 5; state.score += 20; liveStatus('Ogre defeated! +5 coins.'); } } }); if (live.boss && live.boss.alive && Math.abs(live.boss.x - hitX) < reach && Math.abs(live.boss.y - live.y) < 90) { live.boss.hp -= damage; if (live.boss.hp <= 0) { live.boss.alive = false; liveLevel().boss = true; state.coins += 100; state.score += 100 + live.section * 50 + live.level * 10; liveStatus(`${realms[live.section][2]} defeated! +100 coins.`); } } liveRender(); }
function livePickup() { if (!liveLevel().boss) return liveStatus('Defeat the boss first.'); if (liveLevel().item) return liveStatus('Special item already collected.'); liveLevel().item = true; if (liveIndex() < 69) liveUnlocked[liveIndex() + 1] = true; liveStatus(`${realms[live.section][3]} collected! Next level unlocked.`); liveRender(); }
function liveNext() { if (!liveLevel().item) return liveStatus('Finish the boss and collect its special item first.'); if (liveIndex() >= 69) return liveStatus('You conquered all 70 levels!'); live.level++; if (live.level === 10) { live.section++; live.level = 0; } liveStart(); }
function liveUpdate(dt) { if (!live.started) return; let dx = 0; if (live.keys.a || live.keys.ArrowLeft) dx--; if (live.keys.d || live.keys.ArrowRight) dx++; if (dx) { live.x = Math.max(25, Math.min(815, live.x + dx * 220 * dt)); live.facing = dx; } if (live.keys.w || live.keys.ArrowUp) live.y = Math.max(270, live.y - 120 * dt); if (live.keys.s || live.keys.ArrowDown) live.y = Math.min(350, live.y + 120 * dt); live.vy += 900 * dt; live.y += live.vy * dt; if (live.y >= 350) { live.y = 350; live.vy = 0; live.grounded = true; } else live.grounded = false; live.stamina = Math.min(100, live.stamina + 18 * dt); live.enemies.forEach(e => { if (e.alive && Math.abs(e.x - live.x) > 55) e.x += Math.sign(live.x - e.x) * 38 * dt; }); if (live.boss && live.boss.alive && Math.abs(live.boss.x - live.x) > 110) live.boss.x += Math.sign(live.x - live.boss.x) * 14 * dt; }
function liveDraw() { const c = $('gameCanvas'), x = c.getContext('2d'), w = c.width, h = c.height, realm = realms[live.section], color = ['#4cc58a', '#e9784d', '#74bf62', '#76c9e8', '#579be0', '#b28be8', '#edc65b'][live.section]; x.clearRect(0, 0, w, h); const sky = x.createLinearGradient(0, 0, 0, h); sky.addColorStop(0, '#102b48'); sky.addColorStop(1, color); x.fillStyle = sky; x.fillRect(0, 0, w, h); x.fillStyle = '#17334b'; x.fillRect(0, 245, w, 205); x.fillStyle = '#24524c'; x.fillRect(0, 367, w, 83); x.fillStyle = '#59aa72'; for (let i = 0; i < w; i += 72) x.fillRect(i, 358, 34, 8); live.gems.forEach(g => { if (!g.taken) { x.fillStyle = '#a8dd72'; x.beginPath(); x.moveTo(g.x, g.y - 25); x.lineTo(g.x + 14, g.y); x.lineTo(g.x, g.y + 20); x.lineTo(g.x - 14, g.y); x.fill(); } }); live.enemies.forEach(e => { if (e.alive) { x.fillStyle = '#72bd72'; x.fillRect(e.x - 28, e.y - 72, 56, 72); x.fillStyle = '#b7dc78'; x.beginPath(); x.arc(e.x, e.y - 88, 31, 0, Math.PI * 2); x.fill(); x.fillStyle = '#202b2e'; x.fillRect(e.x - 16, e.y - 93, 7, 7); x.fillRect(e.x + 10, e.y - 93, 7, 7); liveBar(x, e.x - 25, e.y - 112, 50, e.hp / e.max); } }); if (live.boss && live.boss.alive) { x.fillStyle = '#ae6389'; x.fillRect(live.boss.x - 43, live.boss.y - 105, 86, 105); x.fillStyle = '#e58a9d'; x.beginPath(); x.arc(live.boss.x, live.boss.y - 125, 48, 0, Math.PI * 2); x.fill(); liveBar(x, live.boss.x - 55, live.boss.y - 185, 110, live.boss.hp / live.boss.max); } x.save(); x.translate(live.x, live.y); x.scale(live.facing, 1); x.fillStyle = '#59d7ed'; x.fillRect(-21, -53, 42, 53); x.fillStyle = '#f5b27d'; x.beginPath(); x.arc(0, -70, 21, 0, Math.PI * 2); x.fill(); x.fillStyle = '#16243a'; x.fillRect(6, -74, 5, 5); x.strokeStyle = '#fff'; x.lineWidth = 4; x.beginPath(); x.moveTo(17, -38); x.lineTo(57, -62); x.stroke(); x.restore(); x.fillStyle = '#f7c969'; x.font = 'bold 15px monospace'; x.fillText(`REALM ${live.section + 1} · LEVEL ${live.level + 1}`, 20, 27); }
function liveBar(x, px, py, width, value) { x.fillStyle = '#1d2535'; x.fillRect(px, py, width, 6); x.fillStyle = '#ff8170'; x.fillRect(px, py, width * Math.max(0, value), 6); }
function liveRender() { const p = liveLevel(), t = liveTotals(); $('coins').textContent = state.coins; $('score').textContent = state.score; $('weapon').textContent = weapons[state.weapon][0]; $('realmName').textContent = realms[live.section][0]; $('themeName').textContent = realms[live.section][1]; $('bossName').textContent = realms[live.section][2]; $('levelNumber').textContent = String(live.level + 1).padStart(2, '0'); $('ogreProgress').textContent = `${p.ogres} / ${t.ogres}`; $('materialProgress').textContent = `${p.materials} / ${t.materials}`; $('ogreBar').style.width = `${p.ogres / t.ogres * 100}%`; $('materialBar').style.width = `${p.materials / t.materials * 100}%`; renderLiveMap(); liveDraw(); }
function renderLiveMap() { $('levelGrid').innerHTML = realms.map((r, s) => `<div class="section-column"><h3>${s + 1}. ${r[0]}</h3><div class="levels">${Array.from({ length: 10 }, (_, l) => { const i = s * 10 + l, p = liveLevels[i], cls = !liveUnlocked[i] ? 'locked' : s === live.section && l === live.level ? 'current' : p.item ? 'done' : ''; return `<button class="level ${cls}" data-live-level="${s}-${l}" ${!liveUnlocked[i] ? 'disabled' : ''}>${l + 1}</button>`; }).join('')}</div></div>`).join(''); document.querySelectorAll('[data-live-level]').forEach(b => b.onclick = () => { const [s, l] = b.dataset.liveLevel.split('-').map(Number); live.section = s; live.level = l; liveStart(); }); }
document.querySelector('#startBtn').onclick = liveStart; document.querySelector('#gatherBtn').onclick = liveCollect; document.querySelector('#ogreBtn').onclick = () => liveStatus('Move beside an ogre and press J, K, or L.'); document.querySelector('#bossBtn').onclick = () => liveStatus('Move beside the boss and attack it.'); document.querySelector('#itemBtn').onclick = livePickup; document.querySelector('#nextBtn').onclick = liveNext;
window.addEventListener('keydown', e => { live.keys[e.key] = true; if (e.key === 'e' || e.key === 'E') liveCollect(); if (e.key === 'j' || e.key === 'J') liveHit('light'); if (e.key === 'k' || e.key === 'K') liveHit('heavy'); if (e.key === 'l' || e.key === 'L') liveHit('ability'); if (e.code === 'Space' && live.grounded) { live.vy = -470; live.grounded = false; } }); window.addEventListener('keyup', e => live.keys[e.key] = false);
let liveLast = performance.now(); function liveLoop(now) { const dt = Math.min(.035, (now - liveLast) / 1000); liveLast = now; liveUpdate(dt); liveDraw(); requestAnimationFrame(liveLoop); } liveRender(); requestAnimationFrame(liveLoop);
animate = function() {};
draw = liveDraw;
