import * as THREE from 'https://cdn.jsdelivr.net/npm/three@0.161.0/build/three.module.js';

const $=id=>document.getElementById(id);
const realms=[['Meadow of Beginnings','Gorak the Rootbound','Rootheart Charm',0x438b63],['Ashen Mines','Brakka Flame-Eater','Ember Core',0xc75b39],['Whispering Woods','The Moss Widow','Mosscloak',0x527d4c],['Frozen Reach','Ymir Stonehide','Frost Titan Shard',0x5d98b0],['Sunken Ruins','Drownmaw','Tidecaller Pearl',0x346b9c],['Storm Citadel','Voltus Prime','Storm Lens',0x7657a9],["Ogre King's Throne",'Ogron, King of Ogres','Crown of the Ogre King',0xb48b42]];
const weapons=[['Rusty Sword',12,0],['Twin Daggers',20,80],['War Hammer',35,180],['Storm Bow',50,320],['SUNBLADE',90,500]];
const state={s:0,l:0,coins:0,score:0,w:0,started:false,keys:{},player:null,enemies:[],gems:[],boss:null,item:null,levels:Array.from({length:70},()=>({o:0,m:0,b:false,i:false})),open:Array(70).fill(false)};state.open[0]=true;
const scene=new THREE.Scene(),camera=new THREE.PerspectiveCamera(52,1,.1,200),renderer=new THREE.WebGLRenderer({canvas:$('gameCanvas'),antialias:true});renderer.shadowMap.enabled=true;scene.add(new THREE.HemisphereLight(0xc3e9ff,0x1b251c,2));const sun=new THREE.DirectionalLight(0xfff1d4,3);sun.position.set(-8,14,10);sun.castShadow=true;scene.add(sun);const world=new THREE.Group();scene.add(world);
const current=()=>state.levels[state.s*10+state.l],total=()=>({o:3+(state.l+1)%4,m:4+(state.l+1)%5}),mat=c=>new THREE.MeshStandardMaterial({color:c,roughness:.68,metalness:.08});
function resize(){const r=$('gameCanvas').parentElement.getBoundingClientRect(),w=Math.max(320,r.width),h=Math.max(240,w*.535);renderer.setSize(w,h,false);camera.aspect=w/h;camera.updateProjectionMatrix();}addEventListener('resize',resize);
function cube(size,color,pos){const m=new THREE.Mesh(new THREE.BoxGeometry(...size),mat(color));m.position.set(...pos);m.castShadow=m.receiveShadow=true;world.add(m);return m;}
function clear(){while(world.children.length)world.remove(world.children[0]);}
function character(pos,color,boss=false){const g=new THREE.Group();g.position.set(...pos);const body=new THREE.Mesh(new THREE.CapsuleGeometry(boss?.75:.42,boss?1.6:1.1,8,12),mat(color));body.position.y=boss?1.1:.7;body.castShadow=true;g.add(body);const head=new THREE.Mesh(new THREE.SphereGeometry(boss?.7:.38,16,12),mat(boss?0xde8990:0xf0b18a));head.position.y=boss?2.4:1.55;head.castShadow=true;g.add(head);world.add(g);return g;}
function spawn(){clear();const r=realms[state.s],p=current(),t=total();cube([36,.35,14],0x304c3d,[0,-.2,0]);for(let n=-15;n<16;n+=2)cube([.03,.02,14],0x527460,[n,.02,0]);state.player=character([0,1,0],0x55cbe0);state.enemies=[];for(let i=p.o;i<t.o;i++)state.enemies.push(character([-8+i*4,1,0],0x73a75e));state.gems=[];for(let i=p.m;i<t.m;i++){const g=new THREE.Mesh(new THREE.OctahedronGeometry(.42),mat(0xa8dd72));g.position.set(-9+i*4,1,-2+(i%2)*4);g.castShadow=true;world.add(g);state.gems.push(g);}state.boss=p.b?null:character([11,2,0],0xb25771,true);state.item=p.i?null:new THREE.Mesh(new THREE.OctahedronGeometry(.5),mat(0xf7c969));if(state.item){state.item.position.set(11,1.2,-2);world.add(state.item);}camera.position.set(0,6,15);camera.lookAt(0,1,0);}
function say(t){$('status').textContent=t;$('toast').textContent=t;$('toast').classList.add('show');clearTimeout(say.timer);say.timer=setTimeout(()=>$('toast').classList.remove('show'),2200);}
function start(){state.started=true;spawn();say(`Level ${state.l+1}: collect materials, defeat ogres, then fight ${realms[state.s][1]}.`);render();}
function collect(){if(!state.started)return say('Start the adventure first.');const g=state.gems.find(x=>x.parent&&x.position.distanceTo(state.player.position)<2.2);if(!g)return say('Move beside a glowing crystal and press E.');world.remove(g);state.gems.splice(state.gems.indexOf(g),1);current().m++;say(`Material gathered: ${current().m} / ${total().m}`);render();}
function attack(kind){if(!state.started)return;const reach=kind==='ability'?5:kind==='heavy'?3.3:2.5,damage=weapons[state.w][1]*(kind==='ability'?2.4:kind==='heavy'?1.7:1),targets=state.enemies.filter(e=>e.parent&&e.position.distanceTo(state.player.position)<reach);if(targets.length){const e=targets[0];world.remove(e);state.enemies.splice(state.enemies.indexOf(e),1);current().o++;state.coins+=5;state.score+=20;say('Ogre defeated! +5 coins.');}else if(state.boss&&state.boss.position.distanceTo(state.player.position)<reach){state.boss.scale.multiplyScalar(.7);state.boss.userData.hp=(state.boss.userData.hp||260)-damage;if(state.boss.userData.hp<=0){world.remove(state.boss);state.boss=null;current().b=true;state.coins+=100;state.score+=100+state.s*50+state.l*10;state.item=new THREE.Mesh(new THREE.OctahedronGeometry(.5),mat(0xf7c969));state.item.position.set(11,1.2,-2);world.add(state.item);say(`Boss defeated! +100 coins. Collect the special item.`);}else say(`${kind} attack dealt ${Math.round(damage)} damage.`);}else say('Move close to an enemy and attack.');render();}
function pickup(){if(!state.item||state.item.position.distanceTo(state.player.position)>2.5)return say('Defeat the boss, then move beside its item.');world.remove(state.item);state.item=null;current().i=true;if(state.s*10+state.l<69)state.open[state.s*10+state.l+1]=true;say(`${realms[state.s][2]} collected! Next level unlocked.`);render();}
function next(){if(!current().i)return say('Collect the boss item before continuing.');if(state.s*10+state.l===69)return say('You conquered all 70 levels!');state.l++;if(state.l===10){state.s++;state.l=0;}start();}
function move(dt){if(!state.started)return;let x=(state.keys.d||state.keys.ArrowRight?1:0)-(state.keys.a||state.keys.ArrowLeft?1:0),z=(state.keys.s||state.keys.ArrowDown?1:0)-(state.keys.w||state.keys.ArrowUp?1:0);if(x||z){const v=new THREE.Vector3(x,0,z).normalize();state.player.position.addScaledVector(v,5*dt);state.player.position.x=THREE.MathUtils.clamp(state.player.position.x,-15,15);state.player.position.z=THREE.MathUtils.clamp(state.player.position.z,-5,5);state.player.rotation.y=x>0?0:Math.PI;}state.gems.forEach(g=>g.rotation.y+=dt*2);state.enemies.forEach(e=>{if(e.position.distanceTo(state.player.position)>1.6)e.position.addScaledVector(state.player.position.clone().sub(e.position).setY(0).normalize(),dt*.8);});camera.lookAt(state.player.position.x,1,state.player.position.z);}
function render(){const r=realms[state.s],p=current(),t=total();$('coins').textContent=state.coins;$('score').textContent=state.score;$('weapon').textContent=weapons[state.w][0];$('realmName').textContent=r[0];$('themeName').textContent='3D realm';$('bossName').textContent=r[1];$('levelNumber').textContent=String(state.l+1).padStart(2,'0');$('ogreProgress').textContent=`${p.o} / ${t.o}`;$('materialProgress').textContent=`${p.m} / ${t.m}`;$('ogreBar').style.width=`${p.o/t.o*100}%`;$('materialBar').style.width=`${p.m/t.m*100}%`;$('levelGrid').innerHTML=realms.map((v,s)=>`<div class="section-column"><h3>${s+1}. ${v[0]}</h3><div class="levels">${Array.from({length:10},(_,l)=>{const i=s*10+l,c=!state.open[i]?'locked':s===state.s&&l===state.l?'current':state.levels[i].i?'done':'';return `<button class="level ${c}" data-level="${s}-${l}" ${!state.open[i]?'disabled':''}>${l+1}</button>`}).join('')}</div></div>`).join('');document.querySelectorAll('[data-level]').forEach(b=>b.onclick=()=>{const [s,l]=b.dataset.level.split('-').map(Number);state.s=s;state.l=l;start();});}
+document.querySelectorAll('.tab').forEach(t=>t.onclick=()=>{document.querySelectorAll('.tab').forEach(x=>x.classList.remove('active'));document.querySelectorAll('.view').forEach(x=>x.classList.remove('active-view'));t.classList.add('active');$(t.dataset.view).classList.add('active-view');});$('startBtn').onclick=start;$('gatherBtn').onclick=collect;$('ogreBtn').onclick=()=>say('Move close to an ogre and use J, K, or L.');$('bossBtn').onclick=()=>say('Move close to the boss and use J, K, or L.');$('itemBtn').onclick=pickup;$('nextBtn').onclick=next;
+addEventListener('keydown',e=>{state.keys[e.key]=true;if(e.key==='e'||e.key==='E')collect();if(e.key==='j'||e.key==='J')attack('light');if(e.key==='k'||e.key==='K')attack('heavy');if(e.key==='l'||e.key==='L')attack('ability');if(e.code==='Space'&&state.player)state.player.position.y=2;});addEventListener('keyup',e=>state.keys[e.key]=false);let last=performance.now();function loop(now){const dt=Math.min(.04,(now-last)/1000);last=now;move(dt);if(state.player&&state.player.position.y>1)state.player.position.y=Math.max(1,state.player.position.y-7*dt);renderer.render(scene,camera);requestAnimationFrame(loop);}resize();render();requestAnimationFrame(loop);
